### ISSUE TITLE
Validate kwargs more strictly

### ISSUE THREAD

**Issue by four43** [jordaneremieff/mangum#172]
A typo that leads to no errors and unexpected functionality is bad. `kwargs` are flexible and a nice way to pass info to the handlers but the handlers should validate that a little more strictly.

@tuukkamustonen had a good idea to validate these.

https://github.com/jordaneremieff/mangum/pull/170#issuecomment-804154942

**Comment by jordaneremieff** [comment]
I've decided that we should avoid using `kwargs` for passing any information to a specific handler's constructor. This is prompted by https://github.com/jordaneremieff/mangum/pull/220 where I've requested `handler_kwargs` and `kwargs` be removed in favor of specific set of keyword arguments that are always available on the adapter and simply ignored in the case that the handler determined by the request context does not make use of it (for now at least).

Probably the adapter should handle these things differently because at the moment there is a bit of inconsistency in how the WebSocket specific arguments are set on the adapter instance, but the only place where the handler constructor is overridden is for the `api_gateway_base_path` behavior for API & HTTP Gateway handlers.
