### ISSUE TITLE
Mangum: 0.12.0 tests folder in pip

### ISSUE THREAD

**Issue by erictwalker18** [jordaneremieff/mangum#194]
There's now a `tests` folder in the most recent release of mangum. Is this intended or is there a way to avoid it?

**Comment by jordaneremieff** [comment]
@erictwalker18 the tests folder would have been included in previous releases, it is not excluded from the package. I think you will need to handle this in your configuration to exclude the tests folder.

**Comment by bradsbrown** [comment]
@jordaneremieff I know this issue is closed, but I'm seeing the same and hitting a problem due to it. I've attached screenshots where I downloaded both v0.11.0 and v0.12.1 directly from the PyPI UI to compare, and you'll notice that v0.12.1 has a `tests` dir at the top level that isn't in v0.11.0, so something appears to have changed in the packaging setup.
![CleanShot 2021-08-09 at 17 38 01](https://user-images.githubusercontent.com/19318157/128783013-9891697f-0b9a-413d-8289-48a3c2c2e191.png)
![CleanShot 2021-08-09 at 17 38 09](https://user-images.githubusercontent.com/19318157/128783021-dd9115a2-d6ba-48df-981e-3aad8a306897.png)

The reason this is a problem is that this `tests` package being installed in my venv clobbers the local `tests` dir within my app, preventing the app from importing from within that directory structure (i.e. `import tests.test_utils` now give me a `ModuleNotFoundError` because the import system is looking within `$VIRTUAL_ENV/lib/python3.9/site-packages/tests/` rather than `(repo root)/tests` and not finding my `test_utils` module).

**Comment by jordaneremieff** [comment]
Thanks for the additional confirmation. I am unable to look into this atm, but to my knowledge nothing has changed to the packaging setup.

I’ll reopen this, if anyone can determine the specifics I will merge/release the fix.

**Comment by bradsbrown** [comment]
@jordaneremieff I pushed a PR this morning that should address the issue.

**Comment by jordaneremieff** [comment]
Thanks @bradsbrown. Released in 0.12.2.
