### ISSUE TITLE
Support multiple serverless platforms

### ISSUE THREAD

**Issue by lsorber** [jordaneremieff/mangum#86]
This comment [1] explains how to use Mangum with the serverless framework. Since serverless supports multiple providers (e.g., Azure), would it be possible that Mangum enables ASGI support for other providers too?

[1] https://dev.to/anilgrexit/comment/gkfo

**Comment by erm** [comment]
So initially this is something I was considering [here](https://github.com/erm/mangum/issues/2) and Mangum used to support Azure specifically, but I ended up splitting that support out into a separate package https://github.com/erm/bonnette and have done something similar with Google Cloud Functions in https://github.com/erm/grevillea.

The adapter logic is essentially the same in these projects, but I don't really maintain them. It has crossed my mind to re-add support for multiple providers (or find some way of sharing the adapter logic across the separate projects), but I'm not really sure. I'll leave this issue open, if there is enough interest (even if one or two more people request this support) I'll take a serious look at re-adding it.

**Comment by lsorber** [comment]
That's nice to hear, and thanks for the pointers.

The reason I posted this issue is because I think it would be great to be able to use the awesome FastAPI package across AWS Lambda, Azure Functions, and Google Cloud Functions.

If it helps, here's one other example of people with the same interest: https://github.com/tiangolo/fastapi/issues/812

**Comment by Nagalenoj** [comment]
I was looking to use FastAPI with Google Cloud Funtions and landed over here. Agree with @lsorber .

**Comment by jordaneremieff** [comment]
@Nagalenoj Okay, I'll think about how to approach this, but I probably won't be able to start on it until the end of next month. Most likely I will support multiple providers in this project.

**Comment by jordaneremieff** [comment]
So I started doing some investigation into how I might accomplish this. I'm thinking adapter classes will look like this:

```python
@dataclass
class Adapter:

    options: dict

    def __call__(self, *args) -> Any:
        raise NotImplementedError

    def on_request(self) -> None:
        raise NotImplementedError

    def on_response(self) -> None:
        raise NotImplementedError

    def on_response_error(self) -> None:
        raise NotImplementedError
```

The `options` dict would replace all the platform-specific configuration (e.g. `api_gateway_base_path`) and the main `Mangum` class would still be the common interface for creating the adapter instances and running the ASGI cycles:

```python
@dataclass
class Mangum:
    """
    Creates an adapter instance.

    * **app** - An asynchronous callable that conforms to version 3.0 of the ASGI
    specification. This will usually be an ASGI framework application instance.
    * **lifespan** - A string to configure lifespan support. Choices are `auto`, `on`,
    and `off`. Default is `auto`.
    * **provider** - A string value identifier for the platform. Choices are `aws`,
    `azure`, and `google`. Default is `aws`.
    * **options** - A dictionary mapping of provider-specific configuration.
    """

    app: ASGIApp
    lifespan: str = "auto"
    provider: str = "aws"
    options: dict = field(default_factory=dict)

    def __post_init__(self) -> None:
        if self.lifespan not in ("auto", "on", "off"):  # pragma: no cover
            raise ConfigurationError(
                "Invalid argument supplied for `lifespan`. Choices are: auto|on|off"
            )
        if self.provider == "aws":
            from mangum.adapters.aws import AWSAdapter

            self.adapter = AWSAdapter(self.options)

        elif self.provider == "azure":
            from mangum.adapters.azure import AzureAdapter

            self.adapter = AzureAdapter(self.options)

        elif self.provider == "google":
            from mangum.adapters.google import GoogleAdapter

            self.adapter = GoogleAdapter(self.options)

    def __call__(self, *args) -> dict:
        with ExitStack() as stack:
            if self.lifespan != "off":
                lifespan_cycle: typing.ContextManager = LifespanCycle(
                    self.app, self.lifespan
                )
                stack.enter_context(lifespan_cycle)

            http_cycle = self.adapter(*args)
            response = http_cycle(self.app)

            return response
```

My intention is to implement this with support for Azure and GCF to start since I already have some work to base them on, but it should be able to support any similar platforms. Ideally I can find a way to determine the platform at runtime without specifying the `providers` parameter, otherwise the default configuration will be set to `aws` to avoid breaking existing usage. I'm not sure when I'll have this ready for a PR/release because there is a lot involved to get it properly ready, but I'm slowly working/thinking on it.

**Comment by jordaneremieff** [comment]
I've made some headway on this and have a working PoC that supports AWS Lambda, Azure, and Google Cloud Functions like this:

```python
from mangum import Mangum

handler = Mangum(app, provider="azure") # aws, google
```

However, I think I won't go ahead with including it in this package directly. I'll explain how I came to this conclusion.

**Initial implementation**

Azure has been a bit tricky because it expects specific parameter names to be defined in the definition of the handler method. In this case, the parameters for `Mangum.__call__` need to match the content of the `function.json` (generally advertised as `req` by default) which conflicts with the AWS Lambda use-case because of the additional `context` parameter. 

There are a couple ways I tried to solve this problem that worked:

1. Treat `Mangum` as a factory by either overriding `__new__` or converting it from a class to a function and returning the callable adapter instances.
2. Create new classes for additional services (e.g. `MangumAzure`) to be imported instead of `Mangum`.

I preferred solution 1 because I want this library to always be as easy-to-use as possible. The difference between `from mangum import Mangum` and `from mangum import Mangum<Provider>` is a design constraint I imposed on myself after removing the initial Azure support to avoid significant backwards-incompatible changes/too much feature creep. It might seem pedantic, but it has proven useful when approaching these larger features.

**Problem**

After doing some further investigation I ran across https://github.com/Azure/azure-functions-python-worker/issues/165. The `azure-functions-python-worker` introduced a WSGI middleware, so it probably makes more sense to PR ASGI support into that package rather than trying to shoe-horn support into this package directly. In the case of Google Cloud Functions, perhaps that will offer greater ASGI support in future  as well - it already uses Flask requests, so it doesn't seem outside of the realm of possibility as ASGI grows in popularity.

The maintenance burden of keeping up with these external developments is quite high, especially since I only really use AWS Lambda myself.

**Conclusion**

I don't think it makes sense to include support directly, but there are still potentially ways to share the generic behaviour for other use-cases/packages - I'll have to think about what this means exactly, will keep this issue open and update it with my thoughts later.

**Comment by jordaneremieff** [comment]
I created an issue [here](https://github.com/Azure/azure-functions-python-library/issues/75) to explore the Azure use-case.

**Comment by lsorber** [comment]
Makes sense @jordaneremieff. Thank you for taking the time to explore what a solution could look like, and for helping to kick-start a proper integration.

Unrelated: you've got some creative project names, how do you come up with those if I may ask?

**Comment by jordaneremieff** [comment]
@lsorber No worries. I think most of what is in here can be re-purposed without too much effort. I'll base anything further about this on how the Azure functions library might approach ASGI, will just let this ticket hang around in the meantime. I might just end up copying over anything relevant from Mangum to Grevillea specifically when I next look into GCF.

Also, Mangum & Bonnette are named after my two favourite musicians, Jeff Mangum of Neutral Milk Hotel and Sean Bonnette of AJJ. Grevillea (spider flower) is the genus of my favourite plant, Grevillea Buxifolia. :)
